version: "3"
services:
  # Ruby on Rails application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -e development -b '0.0.0.0'
    environment:
      PGHOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      RAILS_ENV: development
      PGDBNAME: job_service_development
      LOGSTASH_HOST: logstash
    volumes:
      - .:/app
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - elknetwork

  # PostgreSQL database
  db:
    image: postgres:15
    environment:
      PGHOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      RAILS_ENV: development
      PGDBNAME: job_service_development
    volumes:
      - "postgresDB:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - elknetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elknetwork

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    hostname: kibana
    container_name: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork

  logstash:
    build: ./logstash
    hostname: logstash
    container_name: logstash
    command: logstash -f /conf/logstash.conf
    ports:
      - 5044:5044
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork

volumes:
  postgresDB:

networks:
  elknetwork:
    driver: bridge
