version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.7.0
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elknetwork

  kibana:
    image: kibana:7.7.0
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork

  logstash:
    image: docker.elastic.co/logstash/logstash:7.7.0
    ports:
      - 9600:9600
      - 8089:8089
      - 5000:5000
    volumes:
      - ./logstash:/usr/share/logstash/pipeline/
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork

  # Postgre DB
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      PGHOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      RAILS_ENV: development
      PGDBNAME: job_service_development
    volumes:
      - postgresDB:/var/lib/postgresql/data
    networks:
      - elknetwork

  # Job Service API
  web:
    build: .
    command: bundle exec rails s -p 3000 -e development -b '0.0.0.0'
    environment:
      PGHOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      RAILS_ENV: development
      PGDBNAME: job_service_development
      LOGSTASH_HOST: logstash
    ports:
      - "3000:3000"
    volumes:
      - bundle:/bundle:Z
      - .:/app:Z
    depends_on:
      - db
    networks:
      - elknetwork

networks:
    elknetwork:
        driver: bridge

volumes:
  elasticsearch: {}
  bundle: {}
  postgresDB: {}
