---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/v1/jobs":
    get:
      summary: list jobs
      responses:
        '200':
          description: successful
    post:
      summary: create job
      parameters:
      - name: job
        in: body
        schema:
          type: object
          properties:
            job:
              type: object
              properties:
                job_type_id:
                  type: string
                  example: 39
                company_id:
                  type: string
                title:
                  type: string
                description:
                  type: string
                requirements:
                  type: string
                expired_date:
                  type: string
                status:
                  type: integer
                location:
                  type: string
                no_of_vacancies:
                  type: string
              required:
              - company_id
      responses:
        '201':
          description: successful
  "/api/v1/jobs/{id}":
    parameters:
    - name: id
      in: path
      type: string
      required: true
    get:
      summary: show job
      responses:
        '200':
          description: successful
    patch:
      summary: update job
      parameters:
      - name: id
        in: path
        type: string
        required: true
      - name: job
        in: body
        schema:
          type: object
          properties:
            job:
              type: object
              properties:
                job_type_id:
                  type: string
                  default: 40
                company_id:
                  type: string
                title:
                  type: string
                description:
                  type: string
                requirements:
                  type: string
                expired_date:
                  type: string
                status:
                  type: integer
                location:
                  type: string
                no_of_vacancies:
                  type: string
              required:
              - company_id
      responses:
        '200':
          description: successful
    put:
      summary: update job
      parameters:
      - name: id
        in: path
        type: string
        required: true
      - name: job
        in: body
        schema:
          type: object
          properties:
            job:
              type: object
              properties:
                job_type_id:
                  type: string
                  default: 41
                company_id:
                  type: string
                title:
                  type: string
                description:
                  type: string
                requirements:
                  type: string
                expired_date:
                  type: string
                status:
                  type: integer
                location:
                  type: string
                no_of_vacancies:
                  type: string
              required:
              - company_id
      responses:
        '200':
          description: successful
    delete:
      summary: delete job
      responses:
        '204':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
