apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
  labels:
    app.kubernetes.io/created-by: group1-nus
    app.kubernetes.io/type: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: job-service
      app.kubernetes.io/instance: job-service
      app.kubernetes.io/component: service
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "3000"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: job-service
        app.kubernetes.io/instance: job-service
        app.kubernetes.io/component: service
        app.kubernetes.io/created-by: group1-nus
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: ng-hris
      containers:
        - name: job-service
          envFrom:
            - configMapRef:
                name: job-service
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: auth-service-db
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-db
                  key: password
          image: 876708361421.dkr.ecr.ap-southeast-1.amazonaws.com/job-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 30
          #   periodSeconds: 3
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   successThreshold: 3
          #   periodSeconds: 5
          resources:
            {}
            # requests:
            #   memory: "256Mi"
            #   cpu: "500m"
            # limits:
            #   memory: "1Gi"
            #   cpu: "1"
