apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: ExternalName
  externalName: hris-auth-service-db.cpih5nqynn3w.ap-southeast-1.rds.amazonaws.com
  selector:
    app.kubernetes.io/name: job-service
    app.kubernetes.io/instance: job-service
    app.kubernetes.io/component: pgsql
